### ISSUE TITLE
x

### ISSUE THREAD

**Issue by Emiliodelgado6** [cuenca-mx/fast-agave#171]
Me an quitado cerca de 15mil pesos y no responden @matin cuencamx

**Comment by Emiliodelgado6** [comment]
![Screenshot_20230403_191432_WhatsApp](https://user-images.githubusercontent.com/129811105/229663156-6a0bfe30-803e-41cd-b00c-b1b9fac87973.jpg)

**Comment by Emiliodelgado6** [comment]
![Uploading Screenshot_20230403_191436_WhatsApp.jpg…]()

**Comment by Emiliodelgado6** [comment]
![Uploading Screenshot_20230403_191444_WhatsApp.jpg…]()

**Comment by matin** [comment]
Investigo

**Comment by Emiliodelgado6** [comment]
![Screenshot_20230403_191444_WhatsApp](https://user-images.githubusercontent.com/129811105/229665419-580ef6b8-fbaa-4d7c-81f3-633c6c2e0097.jpg)

**Comment by Emiliodelgado6** [comment]
![Uploading Screenshot_20230403_191446_WhatsApp.jpg…]()

**Comment by Emiliodelgado6** [comment]
@matin  agradezco y si es necesario publico aquí la evidencia de mi caso

**Comment by Emiliodelgado6** [comment]
![Screenshot_20230325_201033](https://user-images.githubusercontent.com/129811105/229667133-303e2cc0-355a-41d3-aff3-d2114525a021.jpg)

**Comment by Emiliodelgado6** [comment]
![Uploading Screenshot_20230403_200445_WhatsApp.jpg…]()

@matin

**Comment by matin** [comment]
Estoy revisando

**Comment by Emiliodelgado6** [comment]
> Estoy revisando
Porfavor

**Comment by Emiliodelgado6** [comment]
Noticias? @matin

**Comment by Emiliodelgado6** [comment]
![Screenshot_20230404_195454_WhatsApp](https://user-images.githubusercontent.com/129811105/229961091-68cc8bf3-9a8c-4d68-8e12-e482168cc687.jpg)

**Comment by Emiliodelgado6** [comment]
@ @matin  ???

**Comment by Emiliodelgado6** [comment]
No me van a dar solución? Para hacer públicas toda evidencia de su trato grosero, donde incumplen con todo lo dicho en el contrato firmado c @matin  cuencamx
